export default class Jobs {
    static ALL_JOBS = 'ALL_JOBS';
    static ALL_JOBS_SUCCESSFUL = 'ALL_JOBS_SUCCESSFUL';
    static ALL_JOBS_REJECTED = 'ALL_JOBS_REJECTED';

    static JOB_DETAILS = 'JOB_DETAILS';
    static JOB_DETAILS_SUCCESSFUL = 'JOB_DETAILS_SUCCESSFUL';
    static JOB_DETAILS_REJECTED = 'JOB_DETAILS_REJECTED';

}