export default class Jobs {
    static ALL_JOBS = 'ALL_JOBS';
    static ALL_JOBS_SUCCESSFUL = 'ALL_JOBS_SUCCESSFUL';
    static ALL_JOBS_REJECTED = 'ALL_JOBS_REJECTED';

    static JOB_DETAILS = 'JOB_DETAILS';
    static JOB_DETAILS_SUCCESSFUL = 'JOB_DETAILS_SUCCESSFUL';
    static JOB_DETAILS_REJECTED = 'JOB_DETAILS_REJECTED';

    static APPLIED_JOBS_LIST = 'APPLIED_JOBS_LIST';
    static APPLIED_JOBS_LIST_SUCCESSFUL = 'APPLIED_JOBS_LIST_SUCCESSFUL';
    static APPLIED_JOBS_LIST_REJECTED = 'APPLIED_JOBS_LIST_REJECTED';

    

}